<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'product_code' => 'CIG001',
                'name' => 'Marlboro Red',
                'description' => 'Premium cigarette brand',
                'category' => 'Cigarettes',
                'price' => 15.00,
                'cost_price' => 12.00,
                'quantity' => 50,
                'min_stock' => 10,
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'product_code' => 'CIG002',
                'name' => 'Camel Blue',
                'description' => 'Smooth taste cigarette',
                'category' => 'Cigarettes',
                'price' => 14.00,
                'cost_price' => 11.00,
                'quantity' => 45,
                'min_stock' => 10,
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'product_code' => 'DRK001',
                'name' => 'Coca Cola 500ml',
                'description' => 'Refreshing cola drink',
                'category' => 'Beverages',
                'price' => 25.00,
                'cost_price' => 18.00,
                'quantity' => 100,
                'min_stock' => 20,
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'product_code' => 'DRK002',
                'name' => 'Sprite 500ml',
                'description' => 'Lemon-lime soda',
                'category' => 'Beverages',
                'price' => 25.00,
                'cost_price' => 18.00,
                'quantity' => 80,
                'min_stock' => 20,
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'product_code' => 'SNK001',
                'name' => 'Pringles Original',
                'description' => 'Stackable potato chips',
                'category' => 'Snacks',
                'price' => 85.00,
                'cost_price' => 65.00,
                'quantity' => 30,
                'min_stock' => 5,
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'product_code' => 'SNK002',
                'name' => 'Lay\'s Classic',
                'description' => 'Classic potato chips',
                'category' => 'Snacks',
                'price' => 45.00,
                'cost_price' => 35.00,
                'quantity' => 60,
                'min_stock' => 10,
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'product_code' => 'CAN001',
                'name' => 'Century Tuna Flakes',
                'description' => 'Premium tuna in oil',
                'category' => 'Canned Goods',
                'price' => 35.00,
                'cost_price' => 28.00,
                'quantity' => 40,
                'min_stock' => 8,
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'product_code' => 'CAN002',
                'name' => 'Del Monte Spaghetti Sauce',
                'description' => 'Italian style pasta sauce',
                'category' => 'Canned Goods',
                'price' => 55.00,
                'cost_price' => 42.00,
                'quantity' => 25,
                'min_stock' => 5,
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'product_code' => 'HTH001',
                'name' => 'Paracetamol 500mg',
                'description' => 'Pain reliever and fever reducer',
                'category' => 'Health & Beauty',
                'price' => 8.00,
                'cost_price' => 5.00,
                'quantity' => 200,
                'min_stock' => 50,
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'product_code' => 'HTH002',
                'name' => 'Band Aid Strips',
                'description' => 'Adhesive bandages',
                'category' => 'Health & Beauty',
                'price' => 25.00,
                'cost_price' => 18.00,
                'quantity' => 150,
                'min_stock' => 30,
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('products')->insertBatch($data);
    }
}
